language: node_js
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 10
addons:
  chrome: stable
before_script :
  - npm install -g grunt-cli
after_success:
#  - npx codecov --disable=gcov
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
