sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
addons:
  apt:
    packages:
    - chromium-browser
before_script :
  - npm install -g grunt-cli
  - ls -l /usr/bin/google-chrome
  - ls -l /usr/bin/google-chrome-stable
  - ls -l /usr/bin/chromium-browser
after_success:
  - npm run coveralls
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
